# 4. Logistic Regression

### 공부 시간에 따른 자격증 시험 합격 가능성

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("../data/LogisticRegressionData.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### 데이터 분리

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### 학습 (로지스틱 회귀 모델)

In [4]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

### 예측

In [5]:
# 6시간 공부
classifier.predict([[6]])
# 결과 1 : 합격으로 예측

array([1], dtype=int64)

In [7]:
classifier.predict_proba([[6]]) # 합격 확률 예측
# 불합격 확률 14%, 합격 확률 86%

array([[0.14150735, 0.85849265]])

In [6]:
# 4시간 공부
classifier.predict([[4]])
# 결과 0 : 불합격으로 예측

array([0], dtype=int64)

In [8]:
classifier.predict_proba([[4]]) # 합격 확률 예측
# 불합격 확률 62%, 합격 확률 38%

array([[0.6249966, 0.3750034]])

### 분류 결과 예측 (테스트 세트)

In [9]:
y_pred = classifier.predict(X_test)
y_pred # 예측 값

array([1, 0, 1, 1], dtype=int64)

In [10]:
y_test # 실제 값 (테스트 세트)

array([1, 0, 1, 0], dtype=int64)

In [11]:
X_test # 공부 시간 (테스트 세트)

array([[ 8.6],
       [ 1.2],
       [10. ],
       [ 4.5]])

In [12]:
classifier.score(X_test, y_test) # 모델 평가
# 전체 테스트 세트 4개 중 분류 예측을 맞힌 갯수 3개 -> 3/4 = 0.75

0.75